// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VjWms.Desktop.Infrastructure.SQLite;

#nullable disable

namespace VjWms.Desktop.Infrastructure.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20260815235100_AddLocalEditHistory")]
    partial class AddLocalEditHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.CachedCustomer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CachedCustomers");

                    b.HasData(
                        new
                        {
                            Id = "cus-001",
                            Code = "KH-VNM",
                            LastSyncedAt = "2026-08-15T23:51:00.1867919Z",
                            Name = "Công ty CP Đường Việt Nam"
                        },
                        new
                        {
                            Id = "cus-002",
                            Code = "KH-HPG",
                            LastSyncedAt = "2026-08-15T23:51:00.1867919Z",
                            Name = "Tập đoàn Hòa Phát"
                        },
                        new
                        {
                            Id = "cus-003",
                            Code = "KH-MSN",
                            LastSyncedAt = "2026-08-15T23:51:00.1867919Z",
                            Name = "Tập đoàn Masan"
                        },
                        new
                        {
                            Id = "cus-004",
                            Code = "KH-BMP",
                            LastSyncedAt = "2026-08-15T23:51:00.1867919Z",
                            Name = "Công ty CP Nhựa Bình Minh"
                        },
                        new
                        {
                            Id = "cus-005",
                            Code = "KH-DAP",
                            LastSyncedAt = "2026-08-15T23:51:00.1867919Z",
                            Name = "Công ty CP DAP - Vinachem"
                        });
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.CachedInventory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<double>("ReservedQuantity")
                        .HasColumnType("REAL");

                    b.Property<string>("SnapshotAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("CachedInventories");

                    b.HasData(
                        new
                        {
                            Id = "inv-001",
                            ProductId = "prd-001",
                            Quantity = 25000.0,
                            ReservedQuantity = 0.0,
                            SnapshotAt = "2026-08-15T23:51:00.1872543Z",
                            WarehouseId = "wh-001"
                        },
                        new
                        {
                            Id = "inv-002",
                            ProductId = "prd-002",
                            Quantity = 18000.0,
                            ReservedQuantity = 0.0,
                            SnapshotAt = "2026-08-15T23:51:00.1872543Z",
                            WarehouseId = "wh-001"
                        },
                        new
                        {
                            Id = "inv-003",
                            ProductId = "prd-003",
                            Quantity = 12000.0,
                            ReservedQuantity = 0.0,
                            SnapshotAt = "2026-08-15T23:51:00.1872543Z",
                            WarehouseId = "wh-001"
                        },
                        new
                        {
                            Id = "inv-004",
                            ProductId = "prd-005",
                            Quantity = 8000.0,
                            ReservedQuantity = 0.0,
                            SnapshotAt = "2026-08-15T23:51:00.1872543Z",
                            WarehouseId = "wh-001"
                        },
                        new
                        {
                            Id = "inv-005",
                            ProductId = "prd-010",
                            Quantity = 30000.0,
                            ReservedQuantity = 0.0,
                            SnapshotAt = "2026-08-15T23:51:00.1872543Z",
                            WarehouseId = "wh-001"
                        },
                        new
                        {
                            Id = "inv-006",
                            ProductId = "prd-006",
                            Quantity = 15000.0,
                            ReservedQuantity = 0.0,
                            SnapshotAt = "2026-08-15T23:51:00.1872543Z",
                            WarehouseId = "wh-003"
                        },
                        new
                        {
                            Id = "inv-007",
                            ProductId = "prd-007",
                            Quantity = 5000.0,
                            ReservedQuantity = 0.0,
                            SnapshotAt = "2026-08-15T23:51:00.1872543Z",
                            WarehouseId = "wh-003"
                        },
                        new
                        {
                            Id = "inv-008",
                            ProductId = "prd-001",
                            Quantity = 40000.0,
                            ReservedQuantity = 0.0,
                            SnapshotAt = "2026-08-15T23:51:00.1872543Z",
                            WarehouseId = "wh-004"
                        },
                        new
                        {
                            Id = "inv-009",
                            ProductId = "prd-008",
                            Quantity = 10000.0,
                            ReservedQuantity = 0.0,
                            SnapshotAt = "2026-08-15T23:51:00.1872543Z",
                            WarehouseId = "wh-004"
                        },
                        new
                        {
                            Id = "inv-010",
                            ProductId = "prd-012",
                            Quantity = 7000.0,
                            ReservedQuantity = 0.0,
                            SnapshotAt = "2026-08-15T23:51:00.1872543Z",
                            WarehouseId = "wh-002"
                        });
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.CachedProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSyncedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CachedProducts");

                    b.HasData(
                        new
                        {
                            Id = "prd-001",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Formosa",
                            ProductCode = "CS-50",
                            ProductName = "Caustic Soda Flakes 98%",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-002",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Tokuyama",
                            ProductCode = "CS-LIQ",
                            ProductName = "Caustic Soda Liquid 50%",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-003",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "OCI",
                            ProductCode = "HCL-32",
                            ProductName = "Hydrochloric Acid 32%",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-004",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Olin",
                            ProductCode = "NAOH-P",
                            ProductName = "Sodium Hydroxide Pearls 99%",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-005",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Lotte Chemical",
                            ProductCode = "H2SO4",
                            ProductName = "Sulfuric Acid 98%",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-006",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Yunnan",
                            ProductCode = "STPP",
                            ProductName = "Sodium Tripolyphosphate",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-007",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "BASF",
                            ProductCode = "SLS-P",
                            ProductName = "Sodium Lauryl Sulfate Powder",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-008",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "ISA",
                            ProductCode = "LABSA",
                            ProductName = "Linear Alkylbenzene Sulfonic Acid",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-009",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Nedmag",
                            ProductCode = "CaCl2",
                            ProductName = "Calcium Chloride 74-77%",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-010",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Tata Chemicals",
                            ProductCode = "Na2CO3",
                            ProductName = "Soda Ash Dense 99.2%",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-011",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Church & Dwight",
                            ProductCode = "NaHCO3",
                            ProductName = "Sodium Bicarbonate (Baking Soda)",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-012",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Kemira",
                            ProductCode = "PAC-30",
                            ProductName = "Poly Aluminium Chloride 30%",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-013",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Evonik",
                            ProductCode = "H2O2-50",
                            ProductName = "Hydrogen Peroxide 50%",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-014",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Dow",
                            ProductCode = "EDTA-4",
                            ProductName = "EDTA Tetrasodium 39%",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-015",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Baerlocher",
                            ProductCode = "CA-STE",
                            ProductName = "Calcium Stearate",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-016",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "PMC Biogenix",
                            ProductCode = "ZN-STE",
                            ProductName = "Zinc Stearate",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-017",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "LG Chem",
                            ProductCode = "DOP",
                            ProductName = "Dioctyl Phthalate (DOP)",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-018",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Chemours",
                            ProductCode = "TIO2-R",
                            ProductName = "Titanium Dioxide Rutile R-902+",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-019",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "BASF",
                            ProductCode = "PE-WAX",
                            ProductName = "Polyethylene Wax",
                            Unit = "KG"
                        },
                        new
                        {
                            Id = "prd-020",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1863400Z",
                            Manufacturer = "Weifang Yaxing",
                            ProductCode = "CPE-135",
                            ProductName = "Chlorinated Polyethylene CPE 135A",
                            Unit = "KG"
                        });
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.CachedSupplier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CachedSuppliers");

                    b.HasData(
                        new
                        {
                            Id = "sup-001",
                            Code = "NCC-FMS",
                            LastSyncedAt = "2026-08-15T23:51:00.1865959Z",
                            Name = "Formosa Plastics Corporation"
                        },
                        new
                        {
                            Id = "sup-002",
                            Code = "NCC-TKY",
                            LastSyncedAt = "2026-08-15T23:51:00.1865959Z",
                            Name = "Tokuyama Corporation"
                        },
                        new
                        {
                            Id = "sup-003",
                            Code = "NCC-OCI",
                            LastSyncedAt = "2026-08-15T23:51:00.1865959Z",
                            Name = "OCI Company Ltd."
                        },
                        new
                        {
                            Id = "sup-004",
                            Code = "NCC-BASF",
                            LastSyncedAt = "2026-08-15T23:51:00.1865959Z",
                            Name = "BASF SE"
                        },
                        new
                        {
                            Id = "sup-005",
                            Code = "NCC-TATA",
                            LastSyncedAt = "2026-08-15T23:51:00.1865959Z",
                            Name = "Tata Chemicals Ltd."
                        });
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.CachedUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CachedUsers");

                    b.HasData(
                        new
                        {
                            Id = "usr-001",
                            FullName = "Quản trị viên",
                            LastSyncedAt = "2026-08-15T23:51:00.1869634Z",
                            PasswordHash = "admin123",
                            Permissions = "[\"all\"]",
                            PreferredLanguage = "vi-VN",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = "usr-002",
                            FullName = "Thủ Kho Nghi Sơn",
                            LastSyncedAt = "2026-08-15T23:51:00.1869634Z",
                            PasswordHash = "thukho123",
                            Permissions = "[\"receipt.create\",\"issue.create\",\"inventory.view\"]",
                            PreferredLanguage = "vi-VN",
                            Role = "WarehouseKeeper",
                            Username = "thukho"
                        });
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.CachedWarehouse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSyncedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CachedWarehouses");

                    b.HasData(
                        new
                        {
                            Id = "wh-001",
                            Category = "NoiDiaNS",
                            Code = "KNĐ",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1851112Z",
                            Name = "Kho Nghi Đồng (Nội địa Nghi Sơn)",
                            Type = "Physical"
                        },
                        new
                        {
                            Id = "wh-002",
                            Category = "NoiDiaKhac",
                            Code = "KNĐK",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1851112Z",
                            Name = "Kho Nội Địa Khác",
                            Type = "Physical"
                        },
                        new
                        {
                            Id = "wh-003",
                            Category = "NhapKhau",
                            Code = "KNK",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1851112Z",
                            Name = "Kho Nhập Khẩu",
                            Type = "Virtual"
                        },
                        new
                        {
                            Id = "wh-004",
                            Category = "XuatKhau",
                            Code = "KXK",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1851112Z",
                            Name = "Kho Xuất Khẩu",
                            Type = "Virtual"
                        },
                        new
                        {
                            Id = "wh-005",
                            Category = "ChuyenKhau",
                            Code = "KCK",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1851112Z",
                            Name = "Kho Chuyển Khẩu",
                            Type = "Virtual"
                        },
                        new
                        {
                            Id = "wh-006",
                            Category = "CCDC",
                            Code = "KCCDC",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1851112Z",
                            Name = "Kho Công Cụ Dụng Cụ",
                            Type = "Physical"
                        },
                        new
                        {
                            Id = "wh-007",
                            Category = "Logistics",
                            Code = "KLOG",
                            IsActive = true,
                            LastSyncedAt = "2026-08-15T23:51:00.1851112Z",
                            Name = "Kho Logistics",
                            Type = "Physical"
                        });
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalAttachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerifiedOnServer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerStoragePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SyncStatus");

                    b.ToTable("LocalAttachments");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalEditHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EditHistories");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalStockIssue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryTerm")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverIdCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SealNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SyncStatus");

                    b.ToTable("LocalStockIssues");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalStockIssueItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfBags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackagingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QrScannedData")
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("LocalStockIssueItems");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalStockReceipt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverIdCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SyncStatus");

                    b.ToTable("LocalStockReceipts");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalStockReceiptItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfBags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackagingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QrScannedData")
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("LocalStockReceiptItems");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalTransfer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestWarehouseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceWarehouseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SyncStatus");

                    b.ToTable("LocalTransfers");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalTransferItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("SourceLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TransferId");

                    b.ToTable("LocalTransferItems");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.SyncLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsRejected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsUploaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.SyncMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SyncMetadata");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalStockIssueItem", b =>
                {
                    b.HasOne("VjWms.Desktop.Domain.Entities.LocalStockIssue", "Issue")
                        .WithMany("Items")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalStockReceiptItem", b =>
                {
                    b.HasOne("VjWms.Desktop.Domain.Entities.LocalStockReceipt", "Receipt")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalTransferItem", b =>
                {
                    b.HasOne("VjWms.Desktop.Domain.Entities.LocalTransfer", "Transfer")
                        .WithMany("Items")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalStockIssue", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalStockReceipt", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VjWms.Desktop.Domain.Entities.LocalTransfer", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
